server:
  port: 8081

spring:
  application:
    name: Usuarios-api
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

#logging:
#  level:
#    org.springframework.security: TRACE

#trace
#debug
#info
#warn
#error