server:
  port: 8081

spring:
  application:
    name: Usuarios-api
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

